### ISSUE TITLE
Misleading error message when arguments (for context-powers) are missing

### ISSUE THREAD

**Issue by judithroth** [makandra/consul#21]
Say we have the following power:

```
power :client_notes do |client|
  # ...
end
```

When calling 

```
Power.current.client_note?(note)
```

without giving the context `client` (e.g. `Power.current.client_note?(client, note)`), the error:

```
wrong number of arguments (0 for 1)
```

is thrown, although it needs two arguments instead of one.
#### Assumption

Since the power query methods are dynamically defined, this might be due to a block taking two parameters. This block does not complain when less parameters are given, however, it probably should. Because it currently does not complain, the actual `0 for 1` arguments error occurs later, leading the wrong direction.

**Comment by henning-koch** [comment]
Did the stacktrace actually claim that `wrong number of arguments (0 for 1)` was thrown by a wrongful invocation of `#client_note?`. It probably pointed to `#client_notes` or `#client_note_ids`, which do take a single argument.

**Comment by judithroth** [comment]
```
wrong number of arguments (0 for 1) (ActionView::Template::Error)
      ./app/models/power/note_trait.rb:39:in `block (2 levels) in <module:NoteTrait>'
      /home/judith/.rvm/gems/ruby-2.1.2/gems/consul-0.12.0/lib/consul/power.rb:27:in `default_include_object?'
      /home/judith/.rvm/gems/ruby-2.1.2/gems/consul-0.12.0/lib/consul/power.rb:123:in `block in define_power'
```

**Comment by henning-koch** [comment]
The filtered backtrace is misleading indeed.

Does this also happen when you tell `rspec` or `cucumber` to display the full backtrace (`-b` argument)?

**Comment by judithroth** [comment]
It's the same with the full backtrace.
