### ISSUE TITLE
Integration with RailsAdmin

### ISSUE THREAD

**Issue by goravbhootra** [makandra/consul#24]
Hi,

Any pointers on how this could be integrated with rails_admin would be much appreciated.

Regards,
Gorav

**Comment by henning-koch** [comment]
We don't use RailsAdmin around here, but guessing from the [http://activeadmin.info/docs/3-index-pages.html#index-scopes](http://activeadmin.info/docs/3-index-pages.html#index-scopes) maybe this would work:

```
scope :all, default: true do |posts|
  posts.merge(Power.current.posts)
end
```

**Comment by goravbhootra** [comment]
Thanks for the quick response and apologies for not providing proper details. I am looking for integration with RailsAdmin (https://github.com/sferik/rails_admin).

**Comment by henning-koch** [comment]
Sorry about mixing those two up!
