### ISSUE TITLE
How to whitelist controllers whithout applying skip_power_check

### ISSUE THREAD

**Issue by trkrameshkumar** [makandra/consul#26]
Hi Guys,

How can i whitelist/skip controllers from ``power`` without applying ``skip_power_check`` on every controller.

**Comment by codener** [comment]
Hey @trkrameshkumar, if you don't want power checks for all your controllers, just [remove `require_power_check` from your ApplicationController](https://github.com/makandra/consul#how-to-never-forget-a-power-check).

**Comment by trkrameshkumar** [comment]
@codener Thanks for your quick response, i removed it from application controller and manually applied on all controllers on whichever controllers i want , now it is working as expected thanks
