### ISSUE TITLE
Installing with RubyGems 2.5.2

### ISSUE THREAD

**Issue by gtaschuk** [makandra/consul#29]
I get the following error when installing Consul 0.12.2 with heroku's install of Rubygems (2.5.2).  I have temporarily downgraded consul to 0.12.1 to avoid this.

```
remote:        Gem::Package::PathError: installing into parent path
remote:        /tmp/build_a6d1f29758d44ec21e9968cc99438621/vendor/bundle/ruby/2.3.0/shared/app_root/app
remote:        of
remote:        /tmp/build_a6d1f29758d44ec21e9968cc99438621/vendor/bundle/ruby/2.3.0/gems/consul-0.12.2
remote:        is not allowed
remote:        An error occurred while installing consul (0.12.2), and Bundler cannot continue.
remote:        Make sure that `gem install consul -v '0.12.2'` succeeds before bundling.
```
It installs fine with more recent versions of rubygems, but unfortunately we don't have control over the version that heroku uses.

It doesn't look like there is much difference between 0.12.1 <-> 0.12.2 - mostly my commits to remove rails 5 deprecation warnings for ```*_filter methods```.

Any idea what the the Gem::Package::PathError is about?

**Comment by kratob** [comment]
It's an issue with relative symlinks. Those symlinks live in the `spec` folder, which should not be part of the packaged gem in the first place. I've modified the `gemspec` and release 0.12.3, so the issue should hopefully be resolved.

**Comment by gtaschuk** [comment]
Thanks!
