### ISSUE TITLE
require_power_check raises exception regardless...

### ISSUE THREAD

**Issue by vitobotta** [makandra/consul#33]
Hi, first of all thanks for this gem, I like the idea of scope-based authorisation. I am having a problem with require_power_check though, in that it always raises an exception regardless of whether an action checks against a power. I always get the 

```
Consul::UncheckedPower:
       This controller does not check against a power
```

exception. I checked the source and I saw that at the line https://github.com/makandra/consul/blob/master/lib/consul/controller.rb#L102 it's just raising the exception without verifying if a check against the current power has been done. 

What am I missing here? Thanks in advance!

**Comment by triskweline** [comment]
The error will not be raised when a controller has a `power` directive like this:

```ruby
class UsersController < ApplicationController
  power :users
end
```

This is implemented internally by telling Rails to skip the `before_action :unchecked_power` that you found.

**Comment by vitobotta** [comment]
Looks like I had misunderstood how it works. Thank you for the clarification!
