### ISSUE TITLE
Do not depend on "rails" gem, depend on parts of Rails that Consul uses

### ISSUE THREAD

**Issue by adamniedzielski** [makandra/consul#36]
### Description

Consul specifies a dependency on `rails` gem - https://github.com/makandra/consul/blob/41652d11afdd05b4b03321c92d6f85916cf8920d/consul.gemspec#L20

`rails` is just an "umbrella gem" that depends on all the components of Ruby on Rails framework - https://github.com/rails/rails/blob/86ca5b254109e64edeb6e142e656b8a8c247cac8/rails.gemspec - ActiveSupport, ActionPack, ActiveRecord, ...

I want to avoid installing `actioncable` gem in my Rails application. When Consul specifies `rails` gem as a dependency then `actioncable` becomes my transitive dependency automatically and there is no way to avoid installing it.

### Proposal

Depend only on these parts of Rails that Consul actually uses, for example:

```ruby
gem.add_dependency "railities"
gem.add_dependency "actionview"
```

I'm happy to make a PR if you accept the change.

**Comment by triskweline** [comment]
Thanks for the suggestion. We're happy to accept a PR for this.

I think consul depends on `activerecord`, `activesupport` and `actionpack`.
