### ISSUE TITLE
Consul should not crash when calling singular scope powers with `nil`

### ISSUE THREAD

**Issue by codener** [makandra/consul#38]
`power :images` defines an `#image?` method that is called like this: `power.image?(some_image)`. When `some_image` is blank, the call fails with `Undefined method 'id' for nil:NilClass`. This is caused by `object.id` in line 35 here:

https://github.com/makandra/consul/blob/41652d11afdd05b4b03321c92d6f85916cf8920d/lib/consul/power.rb#L30-L36
I suggest returning an early `false` after line 30 when `object` is nil, because `nil` can never be a valid value for a scope.

I'll be happy to make a PR if you agree.

**Comment by kratob** [comment]
Fine with me.

**Comment by triskweline** [comment]
Frankly I don't think it's the job of the method to deal with `nil` arguments. The API is that you need to pass it an actual object to check for inclusion.

**Comment by codener** [comment]
Still handling the special `nil` argument makes using Consul so much easier. 

Imagine code like `if power.image?(article.image)`. If the article has no image, this power check crashes. A fix would be `if article.image && power.image?(article.image)`, but this is fragile (need to think of it everywhere) and clutters the application with nil checks.

I've seen workarounds like the one below, which still clutter the power definition file, are not DRY and easy to do wrong (i.e. the `#image?` and `#image!` methods of `power :image` are overwritten by the `power :images` call below).

```
  power :image do |image|
    if image && image.published?
      image
    end
  end

  power :images do
    Image.published
  end
```

Consul offers several convenience features like dynamic power access and "querying a power that might be nil", so I think adding this nil check will fit in the row and improve applications employing it.

**Comment by codener** [comment]
Turns out I didn't read the codes right. What I actually need would be a singular power method like  `power.image(image)` that returns either the image record (if accessible), or nil. I'll try building a local solution for that.

**Comment by foobear** [comment]
Sounds like you actually want to say `image if power.image?(image)`. I feel it should not be the job of a Power to perform supply that (or presence checks, as mentioned).

I have successfully done this in the past:

```ruby
class Article
  def visible_image
    image if image && Power.current.image?(image)
  end
end
```

If no power is available, `visible_image` would fail. This was correct in my case, and probably is correct in yours, too. :)
Views or helpers will also be more clear when `article.visible_image` is called.

**Comment by triskweline** [comment]
> Turns out I didn't read the codes right. What I actually need would be a singular power method like power.image(image) that returns either the image record (if accessible), or nil. I'll try building a local solution for that.

Then I'll close this.
