### ISSUE TITLE
Inheriting from power-protected controllers disables power protection for children

### ISSUE THREAD

**Issue by codener** [makandra/consul#40]
It is common practice to have "base controllers" that hold common functionality for parts of an application. Imagine an "admin area" base controller that protects all its child controllers with the same power:

```
class Admin::BaseController < ApplicationController
  power :admin
end

class Admin::UsersController < Admin::BaseController
  ...
end
```

Unfortunately, `Admin::UsersController` has now **lost all power protection!** It does not actually check a power, and it does not even raise `Consul::UncheckedPower`.

The culprit is probably this method, which caches consul guards at the class instance: https://github.com/makandra/consul/blob/41652d11afdd05b4b03321c92d6f85916cf8920d/lib/consul/controller.rb#L70-L72
Inheriting classes won't have any Consul guards.

Also, the power check has been removed by this line in `#power`: https://github.com/makandra/consul/blob/41652d11afdd05b4b03321c92d6f85916cf8920d/lib/consul/controller.rb#L78

Suggested fix: Cache Consul guards properly as `class_attribute`.

**Comment by triskweline** [comment]
Yes, `class_attribute` would be a way to build this.

You would need to something like `self.consul_guards = consul_guards.dup` when inheriting from a `Consul::Controller`. Otherwise adding a guard in the child class would also add a guard in the superclass. There should be a test against this.
