### ISSUE TITLE
Limiting assignable attributes

### ISSUE THREAD

**Issue by KevinColemanInc** [makandra/consul#41]
Certain users can write to certain attributes on our model.  Could you point me in the right direction with how to do with with consul?

For example:

An Admin can flag a post or edit it. `PUT post: { flagged: "because why not?", body: "Removed bad words" }`.
The Author of a post, can edit the post's body `PUT post: { body: "new body" }`.

I don't want to break those out into separate endpoints, as they are both just updating an attribute of the post.

[pundit supports this](https://github.com/varvet/pundit#strong-parameters)

any advice?

**Comment by triskweline** [comment]
Hi @KevinColemanInc .

I would define a power that returns the attribute names that may be set:

```
power :assignable_post_fields do
  if admin?
    [:body, :flagged]
  else
    [:body]
  end
end
```

Then use that power in your controller:

```
def update
  post = Post.find(...)
  assignable_fields = current_power.assignable_post_fields
  post_params = params.require(:post).permit(*assignable_fields)
  post.update_attributes!(post_params)
  redirect_to post
end
```

You might might find [this video useful](http://bizarre-authorization.talks.makandra.com/). It's old and predates Rails' strong params, but it shows how Consul can be used to implement common authorization patterns.

Hope that helped!
