### ISSUE TITLE
Can't skip :check_power action in v1.0.3

### ISSUE THREAD

**Issue by jbirdjavi** [makandra/consul#50]
We have a complex controller structure in which a power is defined at one level, and in a descendant it is skipped.  For example:

```
class AssignmentsController < ApplicationController
  include Consul::Controller
  current_power do
    Power.new(current_user, params[:ministry_id])
  end

  power :assignments, map: {
    [:show] => :showable_assignments,
    [:update] => :updateable_assignments,
  }, as: :assignment_scope

  ...
end

class SystemsAssignmentsController < AssignmentsController
  skip_around_action :with_current_power
  skip_before_action :check_power, raise: false

  ...
end
```

In v1.0.3, the name of the before_action :check_power was removed so that it is no longer named, and therefore we can no longer skip it.  Can this be fixed somehow?

**Comment by kratob** [comment]
Unfortunately, this cannot be trivially changed back, since the old method of "one before action for all powers" was what lead to the security issue in the first place. We would need to add the ability to disable powers as a new feature.
@triskweline: do you feel this is something we should add?

The only potential workaround I see for the time being would be to set a power in the `SystemAssignmentsController` that passes all the power checks, instead of trying to skip them.

**Comment by triskweline** [comment]
> We would need to add the ability to disable powers as a new feature.

I would accept a PR that clears all powers, then lets users add new powers.

The implementation would probably need to re-implement the `:only` and `:except` handling from ` before_action`.

Another workaround for @jbirdjavi might be to move the shared logic to a [Modularity](https://github.com/makandra/modularity) trait that has a required option whether or not to perform authorization:

```
module DoesAssignmentsController
  as_trait do |authorize:|

    if authorize
      include Consul::Controller
      current_power do
        Power.new(current_user, params[:ministry_id])
      end

      power :assignments, map: {
        [:show] => :showable_assignments,
        [:update] => :updateable_assignments,
      }, as: :assignment_scope
      end
    end
    
    ...
  end    
end

class SystemsAssignmentsController < ApplicationController
  include DoesAssignmentsController[authorize: true]
end

class OtherAssignmentsController < ApplicationController
  include DoesAssignmentsController[authorize: false]
end
```
