### ISSUE TITLE
Namespace support

### ISSUE THREAD

**Issue by jclusso** [makandra/consul#52]
Is there a good way to handle a situation where you have different powers for the same objects in different namespaces. For instance we have an Admin namespace that has User powers that differ entirely from the User powers in the main namespace.

**Comment by triskweline** [comment]
We often have this situation in our projects. In this case we would use two separate powers `:users` and `:admin_users`.

**Comment by jclusso** [comment]
@triskweline I was trying to avoid that but I guess that would work.

**Comment by triskweline** [comment]
It's similiar to Rails' naming of routing helpers when you namespace in routes.

When we have completely separate application areas we may also use a different power for each, e.g. a `Frontend::Power` and a `Backend::Power`.
