### ISSUE TITLE
Verifying if a user can create an instance with certain criteria

### ISSUE THREAD

**Issue by contentfree** [makandra/consul#61]
I'm trying to create a power that will ensure this user has permission to create items for a particular company.

I have something like this:
```
power :items do
  Item.where(company_id: @user.company_id)
end
```

but `current_power.item!(new_valid_item)` raises Powerless even though the new_valid_item has the proper company_id. It's true that the set of _existing_ items doesn't contain this new item because it's not persisted yet, but I still need to validate it. What is the proper way of performing this check?

**Comment by dastra-mak** [comment]
Correct me if I'm wrong, but I think you are calling the power check `current_power.item!(new_valid_item)` in a create controller action before saving the record. What you actually should do is write the Item model in a way that it validates the company association. This way you can simply save the item in the controller and you can never forget to check the power.

For this you can use the `assignable_values` gem in [combination with consul](https://github.com/makandra/consul#validating-assignable-values).

**Comment by contentfree** [comment]
We're doing something similar to that, yes, though we're using Inherited Resources to DRY up a bunch of this stuff. It seems that `power crud:` and `creatable_...` should handle this type of call. Should I be manually creating a `power :item` that takes an instance of Item to verify if it's correctly scoped even if it's not persisted yet?

What do you mean by "you can never forget to check the power"?

**Comment by dastra-mak** [comment]
```
class Item < ActiveRecord::Base
  authorize_values_for :company
end

class Power
  ...

  def assignable_item_companies(_item)
    Company.where(id: user.company_id)
  end

end
```
If you define your model like above, an item is only valid if the right company is set. So it's enough to call `new_valid_item.save!` and you can get rid of the manual check `current_power.item!(new_valid_item)` in your controller. If the power is checked on a validation level it's also checked in other parts of your code where an Item might be created. If you always check the power manually before saving, you have to remember to do it in those places as well which you could forget easily.

`power crud: ..., as: :item_scope` indeed does help you. When you build your item using the scope, the `company_id` is already set correctly according to your power:
```
def build_item
  @item = item_scope.build # item.company_id is user.company_id now
  @item.attributes = item_params
end
```

**Comment by contentfree** [comment]
Where does the `authorize_values_for` come from? I must've missed that in the docs.

**Comment by dastra-mak** [comment]
This macro comes from the [assignable_values gem](https://github.com/makandra/assignable_values#obtaining-assignable-values-from-a-consul-power) but is also mentioned in the consul README.
