### ISSUE TITLE
The dynamically generated query method for powers that return empty arrays returns true

### ISSUE THREAD

**Issue by cdhagmann** [makandra/consul#62]
When creating a power that return an `ActiveRecord::Relation`, I have encountered some unexpected behavior.

```ruby
power :updatable_users do
  if @user.admin?
    User.all
  else
    User.none
  end
end
.
.
.
current_user = User.create(admin: false)
current_user.admin?                           # returns false
current_power = Power.new(current_user)
current_power.updatable_users                 # return []
current_power.updatable_users.class           # return User::ActiveRecord_Relation < ActiveRecord::Relation
current_power.updatable_users.any?            # returns false
current_power.updatable_users.blank?          # returns false
current_power.updatable_users?                # returns **true**
```

This is due to this line in the code as `!!current_power.updatable_users` returns true.

https://github.com/makandra/consul/blob/90fdb78c1522708ad7a42d81907f10849f8ec9bb/lib/consul/power.rb#L21

I would expect that the `current_power.updatable_users?` would return the same value as `current_power.updatable_users.blank?`

```ruby
    private def default_include_power?(power_name, *context)
      result = send(power_name, *context)
      return true if result.nil?
      return !result.empty? if result.respond_to?(:empty?)

      !!result
    end
```

**Comment by triskweline** [comment]
This is by design. We need to distinguish between:

- User is not allowed to see the users index screen. In that case the power should return `nil`.
- User is allowed to see the users index screen, but it currently shows an empty list. E.g. a manager that does not currently have reports assigned. In that case the power should return a relation that does not match records, like `User.none` in your example.

**Comment by cdhagmann** [comment]
I can see where you are coming from. Have you thought of doing an explicit check for `.none`? This is a example monkey-patch that would distinguish between `User.all` that happens to return  an empty list and `User.none`.

```ruby
require 'consul/power'

module Consul
  module Power
    private def default_include_power?(power_name, *context)
      result = public_send(power_name, *context)
      return false if result.is_a?(::ActiveRecord::NullRelation)

      !!result
    end
  end
end
```
